name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./CurrencyApplication
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: list files
      run: ls -a
    - name: Restore dependencies
      run: dotnet restore ./CurrencyApplication.sln
    - name: Build
      run: dotnet build -c Release --no-restore Api/Api.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal
